### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aadriya** [DominicTobias/universal-react#28]
webpack: Compiled successfully.
TypeError: Cannot read property 'initialValue' of undefined
    at domOnlyProps (/home/megha/public_html/universal-react/app/containers/header.js:8:22)
    at Header.render (/home/megha/public_html/universal-react/app/containers/header.js:38:741)
    at /home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at null.ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at null.ReactCompositeComponent._renderValidatedComponent (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at null.ReactCompositeComponent.performInitialMount (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at null.ReactCompositeComponent.mountComponent (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.ReactReconciler.mountComponent (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at null.ReactCompositeComponent.performInitialMount (/home/megha/public_html/universal-react/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
![screenshot from 2017-04-13 14-41-41](https://cloud.githubusercontent.com/assets/26130750/24998343/76eaf8b8-2057-11e7-9dad-9f32ef6c543a.png)

**Comment by dominictobias** [comment]
Try with a fresh npm install and let me know, there have been some updates. I'm closing this for now as I don't expect more activity but will reopen if you're still interested in getting it running
